### ISSUE TITLE
Accessing this.context during prepass does not seem to be working

### ISSUE THREAD

**Issue by BartWaardenburg** [sventschui/preact-ssr-prepass#20]
Hey there, I was hoping you could help me out. I noticed that accessing this.context does not seem to be working during the prepass fase.

https://reactjs.org/docs/context.html#classcontexttype

I created a failing test I was hoping you could help solve. #19

**Comment by sventschui** [comment]
Should be fixed with 1.1.3. Feel free to reopen if you still run into this issue
