### ISSUE TITLE
Prepass is not resolving lazy imports

### ISSUE THREAD

**Issue by droganov** [sventschui/preact-ssr-prepass#3]
I'm able to get through the pre-pass stage, but at the render stage, I get pending promise error.

So it looks like lazy imports are not resolved by pre-pass.

I have a boilerplate (the pre-pass error is in the branch prepass-ssr-issue):
https://github.com/r-k-t-a/starter/tree/prepass-ssr-issue

Prepass use:
https://github.com/r-k-t-a/starter/blob/prepass-ssr-issue/src/koa/routes/defaultRoute/defaultRoute.tsx#L40

Lazy imports:
https://github.com/r-k-t-a/starter/blob/prepass-ssr-issue/src/App.tsx

**Comment by sventschui** [comment]
Sorry for the late reply.

The issue is that currently `Suspense` will swallow the thrown promise during prepass. I added a failing test in https://github.com/sventschui/preact-ssr-prepass/pull/11 . I could not yet come up with a nice way to make `Suspense` a no-op during prepass

**Comment by sventschui** [comment]
`preact-ssr-prepass@1.1.0` is now handling Suspense the same way as Fragments and thus fixes this issue.
